### ISSUE TITLE
Choose a source for content.

### ISSUE THREAD

**Issue by AlanLeverenz** [AlanLeverenz/Sentiment#3]
An alternate approach is to setup an API account to assure consistent results.
- [ ] Create an API connection to **rapidapi** (John)

**Comment by Harpster11** [comment]
In terms of getting text content off social media, my experience is that twitter is the only really open platform remaining. Facebook has made it pretty difficult to access meaningful content from strangers, and Pintrest/Instagram/Snapchat aren't really set up to support text comment strings.
